Repository wecode-bootcamp-korea/13-Winted-backend, pull requests merged in 2020-11, with the labels that each got.

#1 winted 모델링
  .gitignore
  company/__init__.py
  company/admin.py
  company/apps.py
  company/migrations/0001_initial.py
  company/migrations/__init__.py
  company/models.py
  company/tests.py
  company/urls.py
  company/views.py
  recommend/__init__.py
  recommend/admin.py
  recommend/apps.py
  recommend/migrations/0001_initial.py
  recommend/migrations/0002_auto_20201104_0214.py
  recommend/migrations/__init__.py
  recommend/models.py
  recommend/tests.py
  recommend/urls.py
  recommend/views.py
  resume/__init__.py
  resume/admin.py
  resume/apps.py
  resume/migrations/0001_initial.py
  resume/migrations/__init__.py
  resume/models.py
  resume/tests.py
  resume/urls.py
  resume/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
  winted/settings.py
  winted/urls.py
Labels: Status: Accepted

#3 [김형욱] feature/company
  company/migrations/0001_initial.py
  company/models.py
  company/tests.py
  company/urls.py
  company/views.py
  recommend/migrations/0001_initial.py
  recommend/migrations/0002_auto_20201105_0958.py
  resume/migrations/0001_initial.py
  user/migrations/0001_initial.py
  winted/settings.py
Labels: Status: 리뷰 요청

#5 Add : 로그인 인가 추가 .(기능구현 문제로인한 데코레이터)
  user/utils.py
Labels: Status: 도움 요청

#6 [김형욱] feature/resume
  .gitignore
  company/migrations/0002_auto_20201107_1231.py
  company/migrations/0003_auto_20201110_1022.py
  company/models.py
  company/tests.py
  company/views.py
  resume/migrations/0002_auto_20201107_1137.py
  resume/migrations/0003_auto_20201107_1145.py
  resume/models.py
  resume/tests.py
  resume/urls.py
  resume/views.py
  user/utils.py
  winted/settings.py
Labels: Status: 리뷰 요청

#4 [박재용]Add:user.views.py 추가
  user/urls.py
  user/utils.py
  user/views.py
  winted/urls.py
Labels: Status: Unit Test 구현중, Status: 리뷰 요청

#7 [김형욱] feature/recommend
  company/migrations/0004_mapinformation.py
  company/models.py
  company/tests.py
  company/urls.py
  company/views.py
  recommend/migrations/0003_auto_20201108_1133.py
  recommend/migrations/0004_auto_20201108_1134.py
  recommend/migrations/0005_auto_20201108_1156.py
  recommend/models.py
  recommend/tests.py
  recommend/urls.py
  recommend/views.py
  resume/tests.py
  resume/views.py
  user/migrations/0002_auto_20201111_1534.py
  user/models.py
  user/utils.py
  winted/settings.py
Labels: Status: 리뷰 요청

#9 [박재용]Add : 카카오 배열 [0] 추가
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청
